// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fundamental_algorithm
CharacterVector fundamental_algorithm(DataFrame p1_init, DataFrame p2_init);
RcppExport SEXP _StableMarriageCarla_fundamental_algorithm(SEXP p1_initSEXP, SEXP p2_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type p1_init(p1_initSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type p2_init(p2_initSEXP);
    rcpp_result_gen = Rcpp::wrap(fundamental_algorithm(p1_init, p2_init));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StableMarriageCarla_fundamental_algorithm", (DL_FUNC) &_StableMarriageCarla_fundamental_algorithm, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_StableMarriageCarla(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
