# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fundamental_algorithm <- function(p1_init, p2_init) {
    .Call(`_StableMarriageCarla_fundamental_algorithm`, p1_init, p2_init)
}

